// Generated by ml/train.py. Do not edit by hand.
export const projectionModelArtifact = {
  "alpha": 56.23413251903491,
  "coefficients": [
    0.31309884942817234,
    2.710709482329783,
    0.31614846646136385,
    0.10647733593182807,
    1.0913100967585831,
    1.1984977336062048,
    1.884437825263582,
    -0.35381245645432813,
    -0.4518602656976185,
    0.05895936461669821,
    0.7394782450983115,
    -0.2379316558594411,
    -0.13633282743600716,
    -0.13585874063605274
  ],
  "features": [
    "avg_points_3",
    "avg_points_5",
    "last_points",
    "points_trend",
    "avg_attempts_3",
    "avg_carries_3",
    "avg_targets_3",
    "avg_receptions_3",
    "avg_tds_3",
    "games_in_window",
    "is_qb",
    "is_rb",
    "is_wr",
    "is_te"
  ],
  "generatedAt": "2026-09-08T03:01:05.499544+00:00",
  "intercept": 8.448175444903828,
  "means": [
    8.423518085765075,
    8.379145465076798,
    8.470575828389958,
    0.04705774262488265,
    3.2118161663371083,
    2.6427587033375275,
    3.194938782032077,
    2.1610841472426947,
    0.3766353086863603,
    4.659476301755648,
    0.1053987656540236,
    0.2642459104799569,
    0.42650847863862423,
    0.2038468452273953
  ],
  "metrics": {
    "baseline": {
      "mae": 4.8428,
      "rmse": 6.8538
    },
    "byPosition": {
      "QB": {
        "baseline": {
          "mae": 7.0861,
          "rmse": 9.0625
        },
        "model": {
          "mae": 6.7316,
          "rmse": 8.3578
        },
        "rows": 438
      },
      "RB": {
        "baseline": {
          "mae": 4.945,
          "rmse": 7.1729
        },
        "model": {
          "mae": 4.6446,
          "rmse": 6.6123
        },
        "rows": 1152
      },
      "TE": {
        "baseline": {
          "mae": 4.0575,
          "rmse": 5.8811
        },
        "model": {
          "mae": 3.797,
          "rmse": 5.3877
        },
        "rows": 909
      },
      "WR": {
        "baseline": {
          "mae": 4.6311,
          "rmse": 6.4719
        },
        "model": {
          "mae": 4.4762,
          "rmse": 6.0216
        },
        "rows": 1826
      }
    },
    "model": {
      "mae": 4.6067,
      "rmse": 6.3348
    }
  },
  "residualStdDev": 6.334784961666202,
  "scales": [
    6.571951911183676,
    6.224271501154704,
    8.115025578037336,
    4.769863046488348,
    9.788231152895936,
    4.805665523011185,
    2.849612854972914,
    1.9737418642621736,
    0.5766773796815478,
    0.6752608532248684,
    0.30706654955014523,
    0.44093084409527933,
    0.49456950602315797,
    0.402856437106612
  ],
  "source": {
    "license": "CC-BY-4.0",
    "name": "nflverse weekly player stats",
    "urlTemplate": "https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_{season}.csv"
  },
  "status": "EXPERIMENTAL",
  "supportedPositions": [
    "QB",
    "RB",
    "WR",
    "TE"
  ],
  "trainedSeasons": [
    2021,
    2024
  ],
  "trainingRows": 16689,
  "validationRows": 4325,
  "validationSeason": 2025,
  "version": "ridge-next-game-ppr-v1"
} as const;
